spring.application.name=account-service
server.port=8081

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/accountdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=IT24102523

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=ridelinkSecretKeyForJwtSigningMustBeAtLeast32BytesLongForHS256
app.jwt.expiration-ms=86400000
