server.port=${SERVER_PORT:8082}

spring.application.name=driver-service
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/driver_db}
spring.data.mongodb.auto-index-creation=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
